- name: Run PowerShell script on Windows
  hosts: windows_machines_nc
  gather_facts: false

  vars:
    ansible_connection: winrm
    ansible_winrm_scheme: https
    ansible_winrm_port: 5986
    ansible_winrm_transport: ntlm
    ansible_winrm_cert_validation: ignore
  
  tasks:   
    - name: Ping the Windows machine
      ansible.windows.win_ping:

    - name: Create destination directory
      ansible.windows.win_shell: New-Item -ItemType Directory -Path C:\Temp -Force

    - name: Copy hello.ps1 script
      ansible.windows.win_copy:
        src: "{{ playbook_dir }}/files/hello.ps1"
        dest: C:\Temp\test.ps1

    - name: Run the script
      ansible.windows.win_shell: C:\temp\test.ps1

    - name: Verify script success
      ansible.windows.win_shell: Get-Content C:\Temp\output.txt
      register: script_output
      ignore_errors: yes

    - name: Debug output of the script
      when: script_output.rc == 0
      ansible.builtin.debug:
        var: script_output.stdout_lines

    - name: Fail if the content was not returned as expected
      when: script_output.rc != 0 and "'Cannot find path" not in script_output.stderr
      ansible.builtin.fail:
        msg: "Script did not run successfully"
